### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by LeeHaoRanRan** [matt-baugh/many-tasks-make-light-work#1]
The data set does not use the MOOD data set?

**Comment by matt-baugh** [comment]
Ah sorry I forgot this as it's only used as an auxiliary dataset for the inter-dataset blending.
The MOOD dataset (for 3D inter-dataset blending) is here: https://www.synapse.org/#!Synapse:syn21343101/wiki/599515
The ImageNET dataset (for 2D inter-dataset blending) is here: https://www.kaggle.com/c/imagenet-object-localization-challenge/overview 
I will update the README to mention these

**Comment by LeeHaoRanRan** [comment]
Sorry, I still want to know about the HCP dataset, is the HCP dataset downloaded as shown in the figure below?
![Snipaste_2024-01-03_11-23-12](https://github.com/matt-baugh/many-tasks-make-light-work/assets/143264748/19448173-76ca-472d-a604-ca5f15bc04bc)

**Comment by matt-baugh** [comment]
Yes I believe so, it's the T2 weighted scans which I use.

**Comment by LeeHaoRanRan** [comment]
Thank you, but there are no file directories in the code in the T2 weights of this dataset
![image](https://github.com/matt-baugh/many-tasks-make-light-work/assets/143264748/e1e5a904-2538-49e6-8e1f-a2677cd19048)
![image](https://github.com/matt-baugh/many-tasks-make-light-work/assets/143264748/cbea212c-214f-4ff6-8bee-6da7e542ecb6)

**Comment by matt-baugh** [comment]
Ah sorry I misremembered. You should download the 3T MRI  structural preprocessed images. To check, download a single sample, it should contain a folder called T1W. Inside that there are lots of .nii.gz files, including 'T1w_acpc_dc_restore_brain.nii.gz', 'T2w_acpc_dc_restore_brain.nii.gz' and 'wmparc.gii.gz' . These are the files I use (look in the preprocessing folder for exactly how they are used). Sorry again for not getting you the right information straight away, let me know if this works

**Comment by LeeHaoRanRan** [comment]
Yes, that's right.This dataset is over 1T and I still have two questions.
1、Have all the data of 1113 patients been used?
2、The data is so large, how can I download only the three files I am interested in?
Thanks again

**Comment by matt-baugh** [comment]
Yes we use data from all patients.
BUT we do not use ALL the data for each sample.
The files we care about ('T1w_acpc_dc_restore_brain.nii.gz', 'T2w_acpc_dc_restore_brain.nii.gz' and 'wmparc.gii.gz') are only ~40MB per patient (much less than the 1GB that is present). Unfortunately, I could not find a way to only download a subset of the files for each patient, so I downloaded all the data, extracted only the useful files, and then deleted the rest. This means the download does take a while, but once you delete all the unnecessary parts it's not too big (~31GB).

**Comment by LeeHaoRanRan** [comment]
OK.Thank you again for your answer

**Comment by matt-baugh** [comment]
No worries :)
